<huge>
<center>

# Introducción a Numpy

In [1]:
import numpy as np

In [2]:
#creacción de un array d n x m dimensiones.
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [3]:
#impresion de un valor en especifico.
valoraciones[0][1]

7

In [4]:
#otra forma de imprimir un valor en concreto.
valoraciones[0,1]

7

In [5]:
#creacion de un arreglo de n x m x p
valoraciones2 = np.array([[[8,7,8,5],[2,6,8,1]],[[2,6,8,1],[8,8,9,5]],[[8,7,8,5],[8,8,9,5]]])
valoraciones2

array([[[8, 7, 8, 5],
        [2, 6, 8, 1]],

       [[2, 6, 8, 1],
        [8, 8, 9, 5]],

       [[8, 7, 8, 5],
        [8, 8, 9, 5]]])

In [6]:
#impresion de un valor especifico en un array de 3 dimensiones.
valoraciones2[0,1,2]

8

In [7]:
#creacion de un array de 0's de 3 dimensiones.
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
#Operaciones entre arrays. 
#creacion de arrays de 1's de 3 dimensiones.
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  7.,  9.,  2.]],

       [[ 3.,  7.,  9.,  2.],
        [ 9.,  9., 10.,  6.]],

       [[ 9.,  8.,  9.,  6.],
        [ 9.,  9., 10.,  6.]]])

In [9]:
#media de todo el array 3dimensional.
np.mean(valoraciones2)

6.25

In [10]:
#media de una dimension en especifico en el array 3dimensional.
np.mean(valoraciones2, axis=0)

array([[6.        , 6.66666667, 8.        , 3.66666667],
       [6.        , 7.33333333, 8.66666667, 3.66666667]])

In [11]:
#media de una dimension en especifica del array 3dimensional.
np.mean(valoraciones2, axis=1)

array([[5. , 6.5, 8. , 3. ],
       [5. , 7. , 8.5, 3. ],
       [8. , 7.5, 8.5, 5. ]])

In [12]:
#media de una dimensión especifica en el array 3dimensional.
np.mean(valoraciones2, axis=2)

array([[7.  , 4.25],
       [4.25, 7.5 ],
       [7.  , 7.5 ]])

In [13]:
#transformacion de un array de 1dimension a 1 de 3dimensiones.
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [14]:
##np.median(df["Column1"])

In [15]:
#creacion de un array de n x n dimensiones, con valores random
np.random.rand(2,2)

array([[0.95455517, 0.73162357],
       [0.51747392, 0.92940306]])

In [16]:
np.random.rand(3,2)

array([[0.95344482, 0.19463356],
       [0.15132098, 0.43397678],
       [0.38339847, 0.90095075]])